picklepath : "path//to//genea//genea2023_dataset//pickle"
ckptpath : "ckpts//"
use_beat : False
traindata_interval : 1.0 # second
epochs : 30
batch_size : 128
learning_rate : 0.001

frame_length : 128
pre_frame : 8
fps : 30

model :
  pose_dim : 78
  pose_embed_dim : 128
  pose_embedder_n_layers : 3
  pose_decoder_n_layers : 3

  motion_embedder_n_layers : 3
  motion_decoder_n_layers : 3
